### ISSUE TITLE
I am getting errors with the Library

### ISSUE THREAD

**Issue by Tezedeth** [esimkowitz/Particle-Keypad-I2C#2]
In file included from sketch\sketch_feb18b.ino.cpp:1:0:

C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.33.0_x86__mdqgnx93n4wtt\hardware\arduino\avr\cores\arduino/Arduino.h:115:0: note: this is the location of the previous definition

 #define bitWrite(value, bit, bitvalue) ((bitvalue) ? bitSet(value, bit) : bitClear(value, bit))

 

In file included from C:\Users\Ya Boi\Documents\Arduino\sketch_feb18b\sketch_feb18b.ino:1:0:

C:\Users\Ya Boi\Documents\Arduino\libraries\Particle-Keypad-I2C-master\src/Keypad_I2C.h:92:37: error: 'PinMode' has not been declared

  virtual void pin_mode(byte pinNum, PinMode mode) {

                                     ^~~~~~~

C:\Users\Ya Boi\Documents\Arduino\sketch_feb18b\sketch_feb18b.ino:5:17: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]

 char* I2CTYPE = "Adafruit_MCP23017";

                 ^~~~~~~~~~~~~~~~~~~

exit status 1
Error compiling for board Arduino Uno.

____________________________________________________________________________________________

I am trying to run your initial example code but I keep getting these errors when I try to compile it. It has something to do with pinMode not being defined i believe.

**Comment by esimkowitz** [comment]
I need some more info in order to properly help. Can you paste the full .ino file here? What IDE are you using? What is the file structure of your sketch folder? Off the top of my head though, make sure you’re including the header file at the top of your program.

**Comment by esimkowitz** [comment]
I'm going to assume this is resolved and close this if I don't hear back in the next couple days
